name: Build & Push ARMv7 Image to GHCR

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Clear Go module cache
        run: go clean -modcache

      - name: Use custom Go proxy
        run: |
          export GOPROXY=direct
          go mod edit -replace=github.com/spacemeshos/poet=github.com/ibez11/poet@v0.10.10-fixed
          rm -f go.sum
          go mod tidy

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Push to GHCR
        run: |
          docker buildx build --platform linux/arm/v7 \
            --build-arg GOARCH=arm \
            --build-arg GOOS=linux \
            -t ghcr.io/${{ github.repository_owner }}/go-spacemesh-armv7:latest \
            --push .
